# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hello < Formula
  desc "Hello World"
  homepage "https://github.com/johnsmyth/hello/blob/main/README.md"
  version "0.0.24"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/johnsmyth/hello/releases/download/v0.0.24/hello_macos.zip"
    sha256 "d7896bda0c08dbdb6a3815a3791bf7e691bbfe8b532aaf11fba0ede4ec6835a0"
  end

  def install
    bin.install "hello"
  end
end
