# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hello < Formula
  desc "Hello World"
  homepage "https://github.com/johnsmyth/hello/blob/main/README.md"
  version "0.0.19"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/johnsmyth/hello/releases/download/v0.0.19/hello_macos.zip"
    sha256 "a37cfbed590978253d8fb79cc958c8d73b12c9f990eeb4900b131d1427e23eb0"
  end

  def install
    bin.install "hello"
  end
end
