# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hello < Formula
  desc "Hello World"
  homepage "https://github.com/johnsmyth/hello/blob/main/README.md"
  version "0.0.23"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/johnsmyth/hello/releases/download/v0.0.23/hello_darwin_amd64.zip"
    sha256 "9f0ccfb2ab3c22fe9b1422ab06d403b356de528ea5841c598d8cc9b99b78dbe9"
  end

  def install
    bin.install "hello"
  end
end
